# Generated by Django 4.0.4 on 2022-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cynthia', '0003_alter_skill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('emailowner', models.CharField(max_length=80)),
                ('para', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactusForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('namesender', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
