# Generated by Django 4.0.4 on 2022-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cynthia', '0004_contact_contactusform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='para',
            field=models.TextField(max_length=200),
        ),
    ]
